version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_DATABASE_DRIVER=postgres
      - APP_DATABASE_DSN=postgres://user:pass@postgres:5432/dbname?sslmode=disable
      - APP_STORAGE_TYPE=s3
      - APP_STORAGE_S3_REGION=us-east-1
      - APP_STORAGE_S3_BUCKET=report-srv-bucket
      - APP_STORAGE_S3_ENDPOINT=http://localstack:4566
      - APP_STORAGE_S3_ACCESS_KEY=test
      - APP_STORAGE_S3_SECRET_KEY=test
      - APP_SERVER_ADDRESS=:8080
      - APP_SERVER_DEBUG=true
    depends_on:
      - postgres
      - localstack

volumes:
  postgres_data:
  localstack_data:
