version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_DSN: ${DB_DSN}
      S3_BASEPATH: ${S3_BASEPATH}
    volumes:
      - ./templates:${S3_BASEPATH}
    command: ["./report"]
volumes:
  db_data:
